project:
  type: book
  output-dir: docs

book:
  title: "SeqHub"
  page-navigation: true
  favicon: assets/favicon.png
  site-url: https://royfrancis.github.io/seqhub
  repo-url: https://github.com/royfrancis/seqhub
  repo-branch: main
  page-footer:
    border: false
    left: "{{< meta current_year >}} Roy Francis • [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
    right: "Published with [Quarto](https://quarto.org/) v{{< meta quarto_version >}}"
  chapters:
    - index.qmd
    - part: "**Bulk RNASeq**"
      chapters:
        - chapters/bulk/index.qmd
    - part: "**Single Cell RNASeq**"
      chapters:
        - chapters/sc/index.qmd
        - chapters/spatial/index.qmd
        - chapters/airr/index.qmd
        - chapters/atacseq/index.qmd
    - part: "**Meta Transcriptomics**"
      chapters:
        - chapters/meta/index.qmd

bibliography: references.bib
csl: apa.csl
#reference-section-title: References
#citeproc: false

format:
  html:
    include-in-header: "assets/fonts/head.html"
    theme:
      - pulse
      - assets/css/styles.scss
    section-numbering: true
    title-block-banner: true
    title-block-banner-color: "#f2f3f4"
    toc: true
    smooth-scroll: true
    bread-crumbs: false
    lightbox: auto
  epub:
    cover-image: assets/cover.png

crossref:
  fig-title: "**Fig**"
  tbl-title: "**Tab**"
  title-delim: "**: **"

knitr:
  opts_chunk:
    results: hold

execute:
  eval: true
  echo: true
  warning: false
  message: false
  freeze: false

filters:
  - assets/custom.lua

